<a href="https://colab.research.google.com/github/Kamilo1133/data-science-bootcamp/blob/main/03_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [50]:
X * Y

array([[6, 0],
       [2, 0]])

In [51]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [53]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [54]:
X @ Y

array([[  3,   6],
       [-12,   0]])